apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-avangels-master-persistent-storage
#  namespace: avangels
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
