apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-efs-pv
  namespace: staraus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
#  storageClassName: efs-filesystem
